# Generated by Django 5.2.4 on 2025-07-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnKayit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogrenci_ad_soyad', models.CharField(max_length=255, verbose_name='Öğrenci Adı Soyadı')),
                ('ogrenci_tc_kimlik_no', models.CharField(max_length=11, unique=True, verbose_name='Öğrenci T.C. Kimlik No')),
                ('dogum_tarihi', models.DateField(verbose_name='Doğum Tarihi')),
                ('adres', models.TextField(verbose_name='Adres')),
                ('tuvalet_egitimi_var', models.BooleanField(choices=[(True, 'VAR'), (False, 'BEZ KULLANIYOR')], default=False, verbose_name='Öğrencinin Tuvalet Eğitimi')),
                ('okul_deneyimi_var', models.BooleanField(choices=[(True, 'VAR'), (False, 'YOK')], default=False, verbose_name='Okul Deneyimi Var mı?')),
                ('okul_devlet_mi', models.BooleanField(blank=True, choices=[(True, 'DEVLET'), (False, 'ÖZEL')], default=False, null=True, verbose_name='Varsa Devlet ya da Özel mi?')),
                ('anne_ad_soyad', models.CharField(max_length=255, verbose_name='Anne Adı Soyadı')),
                ('anne_telefon', models.CharField(max_length=15, verbose_name='Anne Telefon Numarası')),
                ('anne_ogrenim_durumu', models.CharField(max_length=100, verbose_name='Anne Öğrenim Durumu')),
                ('anne_meslek', models.CharField(max_length=100, verbose_name='Anne Mesleği')),
                ('anne_calistigi_kurum', models.CharField(blank=True, max_length=255, null=True, verbose_name='Anne Çalıştığı Kurum')),
                ('anne_durum', models.CharField(choices=[('SAG', 'Sağ'), ('OLU', 'Ölü'), ('OZ', 'Öz'), ('UVEY', 'Üvey')], max_length=50, verbose_name='Anne Sağ-Ölü / Öz-Üvey')),
                ('baba_ad_soyad', models.CharField(max_length=255, verbose_name='Baba Adı Soyadı')),
                ('baba_telefon', models.CharField(max_length=15, verbose_name='Baba Telefon Numarası')),
                ('baba_ogrenim_durumu', models.CharField(max_length=100, verbose_name='Baba Öğrenim Durumu')),
                ('baba_meslek', models.CharField(max_length=100, verbose_name='Baba Mesleği')),
                ('baba_calistigi_kurum', models.CharField(blank=True, max_length=255, null=True, verbose_name='Baba Çalıştığı Kurum')),
                ('baba_durum', models.CharField(choices=[('SAG', 'Sağ'), ('OLU', 'Ölü'), ('OZ', 'Öz'), ('UVEY', 'Üvey')], max_length=50, verbose_name='Baba Sağ-Ölü / Öz-Üvey')),
                ('aylik_net_gelir', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Aylık Net Gelir (TL)')),
                ('ailedeki_cocuk_sayisi', models.IntegerField(verbose_name='Ailedeki Çocuk Sayısı')),
                ('ikamet_edilen_konut_kiraci', models.BooleanField(choices=[(True, 'KİRACI'), (False, 'EV SAHİBİ')], default=False, verbose_name='İkamet Edilen Konut')),
                ('anne_baba_evli', models.BooleanField(choices=[(True, 'EVLİ'), (False, 'AYRI')], default=False, verbose_name='Anne Baba Birliktelik Durumu')),
                ('velayet_kimde', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ayrı İse Velayet Kimde?')),
                ('puan', models.IntegerField(default=0, verbose_name='Puan')),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
            ],
            options={
                'verbose_name': 'Ön Kayıt Başvurusu',
                'verbose_name_plural': 'Ön Kayıt Başvuruları',
            },
        ),
    ]
