# Generated by Django 5.2.4 on 2025-07-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayit_formu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onkayit',
            options={'verbose_name': 'Ön Kayıt', 'verbose_name_plural': 'Ön Kayıtlar'},
        ),
        migrations.RenameField(
            model_name='onkayit',
            old_name='anne_meslek',
            new_name='anne_meslegi',
        ),
        migrations.RenameField(
            model_name='onkayit',
            old_name='anne_telefon',
            new_name='anne_telefon_numarasi',
        ),
        migrations.RenameField(
            model_name='onkayit',
            old_name='baba_meslek',
            new_name='baba_meslegi',
        ),
        migrations.RenameField(
            model_name='onkayit',
            old_name='baba_telefon',
            new_name='baba_telefon_numarasi',
        ),
        migrations.RenameField(
            model_name='onkayit',
            old_name='tuvalet_egitimi_var',
            new_name='ogrencinin_tuvalet_egitimi',
        ),
        migrations.RemoveField(
            model_name='onkayit',
            name='anne_baba_evli',
        ),
        migrations.RemoveField(
            model_name='onkayit',
            name='anne_durum',
        ),
        migrations.RemoveField(
            model_name='onkayit',
            name='baba_durum',
        ),
        migrations.RemoveField(
            model_name='onkayit',
            name='ikamet_edilen_konut_kiraci',
        ),
        migrations.RemoveField(
            model_name='onkayit',
            name='velayet_kimde',
        ),
        migrations.AddField(
            model_name='onkayit',
            name='anne_baba_birliktelik_durumu',
            field=models.CharField(choices=[('evli', 'EVLİ'), ('ayri', 'AYRI')], default='evli', max_length=10, verbose_name='Anne Baba Birliktelik Durumu'),
        ),
        migrations.AddField(
            model_name='onkayit',
            name='anne_sag_olu_oz_uvey',
            field=models.CharField(choices=[('sag', 'SAĞ'), ('olu', 'ÖLÜ'), ('oz', 'ÖZ'), ('uvey', 'ÜVEY')], default='sag', max_length=10, verbose_name='Anne Sağ-Ölü / Öz-Üvey'),
        ),
        migrations.AddField(
            model_name='onkayit',
            name='baba_sag_olu_oz_uvey',
            field=models.CharField(choices=[('sag', 'SAĞ'), ('olu', 'ÖLÜ'), ('oz', 'ÖZ'), ('uvey', 'ÜVEY')], default='sag', max_length=10, verbose_name='Baba Sağ-Ölü / Öz-Üvey'),
        ),
        migrations.AddField(
            model_name='onkayit',
            name='ikamet_edilen_konut',
            field=models.CharField(choices=[('kiraci', 'KİRACI'), ('ev_sahibi', 'EV SAHİBİ')], default='kiraci', max_length=15, verbose_name='İkamet Edilen Konut'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='anne_ad_soyad',
            field=models.CharField(max_length=200, verbose_name='Anne Adı Soyadı'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='anne_calistigi_kurum',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Anne Çalıştığı Kurum'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='baba_ad_soyad',
            field=models.CharField(max_length=200, verbose_name='Baba Adı Soyadı'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='baba_calistigi_kurum',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Baba Çalıştığı Kurum'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='kayit_tarihi',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='ogrenci_ad_soyad',
            field=models.CharField(max_length=200, verbose_name='Öğrenci Adı Soyadı'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='okul_deneyimi_var',
            field=models.BooleanField(choices=[(True, 'VAR'), (False, 'YOK')], default=False, verbose_name='Okul Deneyimi Var Mı?'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='okul_devlet_mi',
            field=models.CharField(blank=True, choices=[('devlet', 'DEVLET'), ('ozel', 'ÖZEL')], max_length=10, null=True, verbose_name='Varsa Devlet Ya Da Özel Mi?'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='puan',
            field=models.IntegerField(default=0),
        ),
    ]
