# Generated by Django 5.2.4 on 2025-07-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayit_formu', '0002_alter_onkayit_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onkayit',
            options={},
        ),
        migrations.RemoveField(
            model_name='onkayit',
            name='ailedeki_cocuk_sayisi',
        ),
        migrations.RemoveField(
            model_name='onkayit',
            name='anne_baba_birliktelik_durumu',
        ),
        migrations.RemoveField(
            model_name='onkayit',
            name='aylik_net_gelir',
        ),
        migrations.RemoveField(
            model_name='onkayit',
            name='baba_ad_soyad',
        ),
        migrations.RemoveField(
            model_name='onkayit',
            name='baba_calistigi_kurum',
        ),
        migrations.RemoveField(
            model_name='onkayit',
            name='baba_meslegi',
        ),
        migrations.RemoveField(
            model_name='onkayit',
            name='baba_ogrenim_durumu',
        ),
        migrations.RemoveField(
            model_name='onkayit',
            name='baba_sag_olu_oz_uvey',
        ),
        migrations.RemoveField(
            model_name='onkayit',
            name='baba_telefon_numarasi',
        ),
        migrations.RemoveField(
            model_name='onkayit',
            name='ikamet_edilen_konut',
        ),
        migrations.RemoveField(
            model_name='onkayit',
            name='kayit_tarihi',
        ),
        migrations.RemoveField(
            model_name='onkayit',
            name='puan',
        ),
        migrations.AddField(
            model_name='onkayit',
            name='kayit_olmak_istedigi_sube',
            field=models.CharField(choices=[('atam', 'Atakum Anaokulu Merkezi'), ('yeni_mahalle', 'Yeni Mahalle Anaokulu'), ('cumhuriyet', 'Cumhuriyet Anaokulu')], default='atam', max_length=50, verbose_name='Kayıt Olmak İstediği Şube'),
        ),
    ]
