# Generated by Django 5.2.4 on 2025-07-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayit_formu', '0003_alter_onkayit_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onkayit',
            options={'verbose_name': 'Ön Kayıt', 'verbose_name_plural': 'Ön Kayıtlar'},
        ),
        migrations.AddField(
            model_name='onkayit',
            name='ailedeki_cocuk_sayisi',
            field=models.IntegerField(default=1, verbose_name='Ailedeki Çocuk Sayısı'),
        ),
        migrations.AddField(
            model_name='onkayit',
            name='anne_baba_birliktelik_durumu',
            field=models.CharField(choices=[('evli', 'EVLİ'), ('ayri', 'AYRI')], default='evli', max_length=10, verbose_name='Anne Baba Birliktelik Durumu'),
        ),
        migrations.AddField(
            model_name='onkayit',
            name='aylik_net_gelir',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Aylık Net Gelir (TL)'),
        ),
        migrations.AddField(
            model_name='onkayit',
            name='baba_ad_soyad',
            field=models.CharField(default='', max_length=200, verbose_name='Baba Adı Soyadı'),
        ),
        migrations.AddField(
            model_name='onkayit',
            name='baba_calistigi_kurum',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Baba Çalıştığı Kurum (Açıkça Belirtiniz)'),
        ),
        migrations.AddField(
            model_name='onkayit',
            name='baba_meslegi',
            field=models.CharField(default='', max_length=100, verbose_name='Baba Mesleği'),
        ),
        migrations.AddField(
            model_name='onkayit',
            name='baba_ogrenim_durumu',
            field=models.CharField(default='', max_length=100, verbose_name='Baba Öğrenim Durumu'),
        ),
        migrations.AddField(
            model_name='onkayit',
            name='baba_sag_olu_oz_uvey',
            field=models.CharField(choices=[('sag', 'SAĞ'), ('olu', 'ÖLÜ'), ('oz', 'ÖZ'), ('uvey', 'ÜVEY')], default='sag', max_length=10, verbose_name='Baba Sağ-Ölü / Öz-Üvey'),
        ),
        migrations.AddField(
            model_name='onkayit',
            name='baba_telefon_numarasi',
            field=models.CharField(default='', max_length=15, verbose_name='Baba Telefon Numarası'),
        ),
        migrations.AddField(
            model_name='onkayit',
            name='ikamet_edilen_konut',
            field=models.CharField(choices=[('kiraci', 'KİRACI'), ('ev_sahibi', 'EV SAHİBİ')], default='kiraci', max_length=15, verbose_name='İkamet Edilen Konut'),
        ),
        migrations.AddField(
            model_name='onkayit',
            name='kayit_tarihi',
            field=models.DateTimeField(auto_now_add=True, default='2023-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onkayit',
            name='puan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='onkayit',
            name='velayet_kimde',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Velayet Kimde?'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='adres',
            field=models.TextField(default='', verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='anne_ad_soyad',
            field=models.CharField(default='', max_length=200, verbose_name='Anne Adı Soyadı'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='anne_calistigi_kurum',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Anne Çalıştığı Kurum (Açıkça Belirtiniz)'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='anne_meslegi',
            field=models.CharField(default='', max_length=100, verbose_name='Anne Mesleği'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='anne_ogrenim_durumu',
            field=models.CharField(default='', max_length=100, verbose_name='Anne Öğrenim Durumu'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='anne_telefon_numarasi',
            field=models.CharField(default='', max_length=15, verbose_name='Anne Telefon Numarası'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='kayit_olmak_istedigi_sube',
            field=models.CharField(choices=[('atakum_anaokulu_merkezi', 'Atakum Anaokulu Merkezi'), ('yeni_mahalle_anaokulu', 'Yeni Mahalle Anaokulu'), ('cumhuriyet_anaokulu', 'Cumhuriyet Anaokulu')], default='atakum_anaokulu_merkezi', max_length=50, verbose_name='Kayıt Olmak İstediği Şube'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='ogrenci_ad_soyad',
            field=models.CharField(default='', max_length=200, verbose_name='Öğrenci Adı Soyadı'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='ogrenci_tc_kimlik_no',
            field=models.CharField(default='00000000000', max_length=11, unique=True, verbose_name='Öğrenci T.C. Kimlik No'),
        ),
    ]
