# Generated by Django 5.2.4 on 2025-07-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayit_formu', '0004_alter_onkayit_options_onkayit_ailedeki_cocuk_sayisi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onkayit',
            name='anne_calistigi_kurum',
        ),
        migrations.RemoveField(
            model_name='onkayit',
            name='anne_meslegi',
        ),
        migrations.RemoveField(
            model_name='onkayit',
            name='anne_telefon_numarasi',
        ),
        migrations.RemoveField(
            model_name='onkayit',
            name='aylik_net_gelir',
        ),
        migrations.RemoveField(
            model_name='onkayit',
            name='baba_calistigi_kurum',
        ),
        migrations.RemoveField(
            model_name='onkayit',
            name='baba_meslegi',
        ),
        migrations.RemoveField(
            model_name='onkayit',
            name='baba_telefon_numarasi',
        ),
        migrations.AddField(
            model_name='onkayit',
            name='anne_aylik_net_gelir',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Anne - Aylık Net Gelir'),
        ),
        migrations.AddField(
            model_name='onkayit',
            name='anne_calisilan_kurum',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Anne - Çalıştığı Kurum'),
        ),
        migrations.AddField(
            model_name='onkayit',
            name='anne_meslek',
            field=models.CharField(default='', max_length=100, verbose_name='Anne - Mesleği'),
        ),
        migrations.AddField(
            model_name='onkayit',
            name='anne_telefon',
            field=models.CharField(default='', max_length=15, verbose_name='Anne - Telefon Numarası'),
        ),
        migrations.AddField(
            model_name='onkayit',
            name='baba_aylik_net_gelir',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Baba - Aylık Net Gelir'),
        ),
        migrations.AddField(
            model_name='onkayit',
            name='baba_calisilan_kurum',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Baba - Çalıştığı Kurum'),
        ),
        migrations.AddField(
            model_name='onkayit',
            name='baba_meslek',
            field=models.CharField(default='', max_length=100, verbose_name='Baba - Mesleği'),
        ),
        migrations.AddField(
            model_name='onkayit',
            name='baba_telefon',
            field=models.CharField(default='', max_length=15, verbose_name='Baba - Telefon Numarası'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='anne_ad_soyad',
            field=models.CharField(default='', max_length=200, verbose_name='Anne - Adı Soyadı'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='anne_ogrenim_durumu',
            field=models.CharField(default='', max_length=100, verbose_name='Anne - Öğrenim Durumu'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='anne_sag_olu_oz_uvey',
            field=models.CharField(choices=[('sag', 'SAĞ'), ('olu', 'ÖLÜ'), ('oz', 'ÖZ'), ('uvey', 'ÜVEY')], default='sag', max_length=10, verbose_name='Anne - Sağ / Ölü / Öz / Üvey'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='baba_ad_soyad',
            field=models.CharField(default='', max_length=200, verbose_name='Baba - Adı Soyadı'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='baba_ogrenim_durumu',
            field=models.CharField(default='', max_length=100, verbose_name='Baba - Öğrenim Durumu'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='baba_sag_olu_oz_uvey',
            field=models.CharField(choices=[('sag', 'SAĞ'), ('olu', 'ÖLÜ'), ('oz', 'ÖZ'), ('uvey', 'ÜVEY')], default='sag', max_length=10, verbose_name='Baba - Sağ / Ölü / Öz / Üvey'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='ogrenci_ad_soyad',
            field=models.CharField(default='', max_length=200, verbose_name='Öğrenci Ad Soyad'),
        ),
    ]
