# Generated by Django 5.2.3 on 2025-07-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayit_formu', '0005_remove_onkayit_anne_calistigi_kurum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onkayit',
            name='anne_sag_olu_oz_uvey',
        ),
        migrations.RemoveField(
            model_name='onkayit',
            name='baba_sag_olu_oz_uvey',
        ),
        migrations.AddField(
            model_name='onkayit',
            name='anne_oz_uvey',
            field=models.CharField(choices=[('oz', 'ÖZ'), ('uvey', 'ÜVEY')], default='oz', max_length=4, verbose_name='Anne - Öz / Üvey'),
        ),
        migrations.AddField(
            model_name='onkayit',
            name='anne_sag_olu',
            field=models.CharField(choices=[('sag', 'SAĞ'), ('olu', 'ÖLÜ')], default='sag', max_length=3, verbose_name='Anne - Sağ / Ölü'),
        ),
        migrations.AddField(
            model_name='onkayit',
            name='baba_oz_uvey',
            field=models.CharField(choices=[('oz', 'ÖZ'), ('uvey', 'ÜVEY')], default='oz', max_length=4, verbose_name='Baba - Öz / Üvey'),
        ),
        migrations.AddField(
            model_name='onkayit',
            name='baba_sag_olu',
            field=models.CharField(choices=[('sag', 'SAĞ'), ('olu', 'ÖLÜ')], default='sag', max_length=3, verbose_name='Baba - Sağ / Ölü'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='adres',
            field=models.TextField(verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='anne_ad_soyad',
            field=models.CharField(max_length=200, verbose_name='Anne - Adı Soyadı'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='anne_aylik_net_gelir',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Anne - Aylık Net Gelir'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='anne_calisilan_kurum',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Anne - Çalıştığı Kurum'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='anne_meslek',
            field=models.CharField(max_length=100, verbose_name='Anne - Mesleği'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='anne_ogrenim_durumu',
            field=models.CharField(choices=[('ilkogretim', 'İlköğretim'), ('ortaokul', 'Ortaokul'), ('lise', 'Lise'), ('universite', 'Üniversite'), ('yukseklisans', 'Yüksek Lisans'), ('doktora', 'Doktora')], max_length=20, verbose_name='Anne - Öğrenim Durumu'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='anne_telefon',
            field=models.CharField(max_length=15, verbose_name='Anne - Telefon Numarası'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='baba_ad_soyad',
            field=models.CharField(max_length=200, verbose_name='Baba - Adı Soyadı'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='baba_aylik_net_gelir',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Baba - Aylık Net Gelir'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='baba_calisilan_kurum',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Baba - Çalıştığı Kurum'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='baba_meslek',
            field=models.CharField(max_length=100, verbose_name='Baba - Mesleği'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='baba_ogrenim_durumu',
            field=models.CharField(choices=[('ilkogretim', 'İlköğretim'), ('ortaokul', 'Ortaokul'), ('lise', 'Lise'), ('universite', 'Üniversite'), ('yukseklisans', 'Yüksek Lisans'), ('doktora', 'Doktora')], max_length=20, verbose_name='Baba - Öğrenim Durumu'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='baba_telefon',
            field=models.CharField(max_length=15, verbose_name='Baba - Telefon Numarası'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='ogrenci_ad_soyad',
            field=models.CharField(max_length=200, verbose_name='Öğrenci Ad Soyad'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='ogrenci_tc_kimlik_no',
            field=models.CharField(max_length=11, unique=True, verbose_name='Öğrenci T.C. Kimlik No'),
        ),
    ]
