# Generated by Django 5.2.4 on 2025-07-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayit_formu', '0006_remove_onkayit_anne_sag_olu_oz_uvey_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onkayit',
            name='kayit_olmak_istedigi_sube',
        ),
        migrations.AddField(
            model_name='onkayit',
            name='birinci_kres_tercihi',
            field=models.CharField(choices=[('secenek_1', 'Seçenek 1'), ('secenek_2', 'Seçenek 2'), ('secenek_3', 'Seçenek 3'), ('secenek_4', 'Seçenek 4')], default='secenek_1', max_length=20, verbose_name='Birinci Kreş Tercihi'),
        ),
        migrations.AddField(
            model_name='onkayit',
            name='ikinci_kres_tercihi',
            field=models.CharField(choices=[('secenek_1', 'Seçenek 1'), ('secenek_2', 'Seçenek 2'), ('secenek_3', 'Seçenek 3'), ('secenek_4', 'Seçenek 4')], default='secenek_2', max_length=20, verbose_name='İkinci Kreş Tercihi'),
        ),
        migrations.AddField(
            model_name='onkayit',
            name='ucuncu_kres_tercihi',
            field=models.CharField(choices=[('secenek_1', 'Seçenek 1'), ('secenek_2', 'Seçenek 2'), ('secenek_3', 'Seçenek 3'), ('secenek_4', 'Seçenek 4')], default='secenek_3', max_length=20, verbose_name='Üçüncü Kreş Tercihi'),
        ),
    ]
