# Generated by Django 5.2.4 on 2025-07-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayit_formu', '0007_remove_onkayit_kayit_olmak_istedigi_sube_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onkayit',
            name='kvkk_onay',
            field=models.BooleanField(default=False, help_text='Kişisel Verilerin Korunması Kanunu kapsamında aydınlatma metnini okudum ve onaylıyorum.', verbose_name='KVKK Aydınlatma Metni Onayı'),
        ),
    ]
