# Generated by Django 5.2.3 on 2025-07-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayit_formu', '0008_onkayit_kvkk_onay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onkayit',
            name='birinci_kres_tercihi',
            field=models.CharField(blank=True, choices=[('secenek_1', 'Seçenek 1'), ('secenek_2', 'Seçenek 2'), ('secenek_3', 'Seçenek 3'), ('secenek_4', 'Seçenek 4')], max_length=20, null=True, verbose_name='Birinci Kreş Tercihi'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='ikinci_kres_tercihi',
            field=models.CharField(blank=True, choices=[('secenek_1', 'Seçenek 1'), ('secenek_2', 'Seçenek 2'), ('secenek_3', 'Seçenek 3'), ('secenek_4', 'Seçenek 4')], max_length=20, null=True, verbose_name='İkinci Kreş Tercihi'),
        ),
        migrations.AlterField(
            model_name='onkayit',
            name='ucuncu_kres_tercihi',
            field=models.CharField(blank=True, choices=[('secenek_1', 'Seçenek 1'), ('secenek_2', 'Seçenek 2'), ('secenek_3', 'Seçenek 3'), ('secenek_4', 'Seçenek 4')], max_length=20, null=True, verbose_name='Üçüncü Kreş Tercihi'),
        ),
    ]
